### ISSUE TITLE
Show formatters and linters instead of `null_ls`

### ISSUE THREAD

**Issue by tnthi115** [dokwork/lualine-ex#25]
Instead of showing `null_ls`, it would be nice to see which formatters and linters are attached to the buffer like in Lunarvim or Astronvim.

![image](https://github.com/dokwork/lualine-ex/assets/44877343/d9154f87-7213-4f28-9cf7-6ba70365e575)

**Comment by vladimir-popov** [comment]
I suppose, it would be better to create a separate component specially for your case. I don't use null_ls, but I'll try to look into it when I will have time

**Comment by vladimir-popov** [comment]
@tnthi115 according to this issue https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621 null-ls is not supported. Do you know an actual fork?

**Comment by vladimir-popov** [comment]
Ok, I've found the answer. The LunarVim already moved to [none-ls.nvim](https://github.com/nvimtools/none-ls.nvim) https://github.com/LunarVim/LunarVim/pull/4392.

**Comment by tnthi115** [comment]
This snippet is probably helpful: https://gist.github.com/Lamarcke/36e086dd3bb2cebc593d505e2f838e07

**Comment by vladimir-popov** [comment]
@tnthi115 check please this PR, is it ok for you, or maybe you have any ideas? https://github.com/dokwork/lualine-ex/pull/26

**Comment by tnthi115** [comment]
@vladimir-popov Great work, thank you! Have you considered extending the `ex.lsp.all` list instead of having a separate component and list for `null_ls` alone?

**Comment by vladimir-popov** [comment]
@tnthi115 I'm still thinking that separate components are better and more flexible. For instance, I find it preferable to utilize the `ex.lsp.all` component in the `only_icons` mode. The specific names of LSP servers are less critical to me. Conversely, when dealing with `null-ls`, it is reasonable to see the full names of actual sources. So, I personally hide an icon for `null-ls` in the `ex.lsp.all` component by setting empty string to it, and it looks like this: 
<img width="140" alt="Screenshot 2023-12-27 at 12 51 00" src="https://github.com/dokwork/lualine-ex/assets/6939832/f1a0b0ad-d594-4b08-b715-9d4f584fd0c5">

Maybe you have use-case in which separate components are not appropriate to you?

**Comment by tnthi115** [comment]
@vladimir-popov I think your example works well. Thank you for your hard work!
