### ISSUE TITLE
[ex.git.branch] disabled color is always used instead of changed or committed ones

### ISSUE THREAD

**Issue by gbcreation** [dokwork/lualine-ex#34]
I added `ex.git.branch` to `sections.lualine_b` without changing the default options and the disabled color is always used whatever the git repository's state is. Is there any tip to debug this issue? What can I check? I use git version 2.46.0.

Thank you for your help.

**Comment by vladimir-popov** [comment]
@gbcreation could you please provide the version of  neovim you're currently using, as well as operation system  you are on?

Additionally, could you try running the following Lua code within nvim while inside a git repository?
```lua
:lua print(require('lualine.ex.git_provider').find_git_root(vim.fs.normalize(vim.fn.getcwd())))
```

**Comment by gbcreation** [comment]
@vladimir-popov here is the version of neovim :

```
:version                                                                                                                                                                                                   
NVIM v0.10.1                                                                                                                                                                                               
Build type: Release                                                                                                                                                                                        
LuaJIT 2.1.1720049189
```

The provided Lua code prints the correct path for the local Git repository.

Additional info to reproduce:
- run neovim
- open a file with `:e` -> the right color is used
- `:vsplit` another file -> the right color is used
- `<C-w>w` to switch to window with the first opened file -> the disabled color is used
- `<C-w>w` again to switch to window with the second opened file -> the disabled color is used

**Comment by vladimir-popov** [comment]
Thank you for sharing details! Do I understand correctly that the branch name is displayed, but appears in a disabled color? And when the disabled color is used, the code above shows the correct git repo path?

**Comment by vladimir-popov** [comment]
Could we conduct a few more experiments to manually debug the component?

Let's create an instance of the component manually (it will create a new global object `CMP` in your nvim session):
```lua
:lua CMP = require('lualine.components.ex.git.branch')({ self = { section = 'c' } })
```

Then the color of the component depends on the result of the follow code:
```lua
:lua print(CMP.git():is_worktree_changed())
```

And the branch name depends on the:
```lua
:lua print(CMP.git():get_branch())
```

Please, try to check both instructions in both cases, when the color is correct and when it's wrong.
After experiments, remove the temp instance:
```lua
:lua CMP = null
```
and share result here (feel free to replace the path with anything you like; what matters to us is that the correct path is returned).

**Comment by gbcreation** [comment]
> Thank you for sharing details! Do I understand correctly that the branch name is displayed, but appears in a disabled color? And when the disabled color is used, the code above shows the correct git repo path?

That's correct.

**Comment by gbcreation** [comment]
Thanks for helping me to dig into the problem.

`is_worktree_changed()` returns the right value true / false depending on whether or not the repository contains changes.
`get_branch()` returns also the right branch name.

What is weird is that the color switches from the _disabled_ one to the _changed_ or _committed_ one as soon as I type `:` to enter the command line. If I quit the command line, hitting `<esc>`, of after running a command, the color stays the good one. But if I focus another window with `<C-w>w`, the color switches to the _disabled_ one again.

Is it a status line refresh issue?

**Comment by vladimir-popov** [comment]
Hm... It looks like the issue really out of the component scope. The `nvim-lualine` has an option to refresh statusline manually: `require('lualine').refresh()`. You can find more details here: https://github.com/nvim-lualine/lualine.nvim?tab=readme-ov-file#refreshing-lualine 

One more thing I can suggest is trying to change `disabled` color for the component to something different (for example, `disabled_color = { fg = 'red' }`).  If the reason is in the component, then it will become "red", otherwise it will have default disabled color.
